export const metadata = {
    title: "Get Started | Task Manager App",
    description: "Generated by create next app",
  };

export default function GetStartedLayout({children}) {
  return (
    
    <div>

        {children}
    </div>
  )
}
