export const metadata = {
    title: "About | Task Manager App",
    description: "Generated by create next app",
  };

export default function AboutLayout() {
  return (
    <div>About Layout Page</div>
  )
}
