export const metadata = {
    title: "Contact | Task Manager App",
    description: "Generated by create next app",
  };

export default function ContactLayout() {
  return (
    <div>Contact Layout</div>
  )
}
