import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const pop = Poppins({ subsets: ["latin"], weight:['400'] });

export const metadata = {
  title: "Task Manager App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pop.className}>
        <Navbar />
        <div className="min-h-[80vh]">
          {children}
        </div>
        <Footer />
        </body>
    </html>
  );
}
